/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
